---
# tasks file for clair

# Not needed as we deploy if quay has already done it
# - name: Add SCC anyuid to default account
#   shell: "oc adm policy add-scc-to-user anyuid -z default -n {{ clair_namespace }}"

- name: Create Clair Postgres
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
  with_items:
  - clair-postgresql-pvc.yml.j2
  - clair-postgresql-deployment.yml.j2
  - clair-postgresql-service.yml.j2

- name: Create Clair App Objects
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
  with_items:
  - clair-app-secret.yml.j2
  - clair-app-cm.yml.j2
  - clair-app-service.yml.j2
  - clair-app-deployment.yml.j2
