---
# tasks file for Quay Enterprise

# Create Project
- name: Create Quay Enterprise project
  openshift_raw:
    api_version: v1
    kind: Project
    name: quay-enterprise
    state: present

- name: Add SCC anyuid to default account
  shell: "oc adm policy add-scc-to-user anyuid -z default -n quay-enterprise"

# Create Objects
- name: Create Quay postgresql objects
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
  with_items:
  - quay-enterprise-postgresql-pvc.yml.j2
  - quay-enterprise-postgresql.yml.j2
  - quay-enterprise-postgresql-service.yml.j2

- name: Create Quay Enterprise Redis objects
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
  with_items:
  - quay-enterprise-redis.yml.j2
  - quay-enterprise-redis-service.yml.j2

- name: Create Quay Enterprise Role and RoleBinding
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
  with_items:
  - quay-enterprise-app-role.yml.j2
  - quay-enterprise-app-rolebinding.yml.j2
  - quay-enterprise-app-service.yml.j2
  - quay-enterprise-app-route.yml.j2
  - quay-enterprise-app-cm.yml.j2
  - quay-enterprise-app-pvc.yml.j2
  - quay-enterprise-app.yml.j2

# - name: Create Quay Enterprise Secret
#   openshift_raw:
#     src: "{{ role_path }}/files/quay-enterprise-config-secret.yml.j2"
 

#  - name: Add SSL certs 
#   block:

#   - name: Create temp folder
#     tempfile:
#       state: directory
#       suffix: ".cert"
#     register: tmp_folder_cert

#   - name: Create CA private key and cert
#     shell: >
#       openssl req -x509 -nodes -keyout "{{ tmp_folder_cert.path }}/ca.key" 
#       -out "{{ tmp_folder_cert.path }}/ca.crt" -newkey rsa:2048 -days 3650 
#       -subj "/CN={{ quay_enterprise_ca_cn }}"

#   - name: Create an OpenSSL server private key
#     shell: openssl genrsa -out "{{ tmp_folder_cert.path }}/server.key" 4096


#   - name: Create server OpenSSL csr
#     shell: >
#       openssl req -new -keyout "{{ tmp_folder_cert.path }}/server.key" -nodes
#       -out "{{ tmp_folder_cert.path }}/server.csr" -subj "/CN={{ quay_enterprise_server_cn }}"

# # openssl ansible modules does not provide CA signing yet, meant for 2.6
#   - name: Save cert extensions
#     template:
#       src: x509_extensions.j2
#       dest: "{{ tmp_folder_cert.path }}/x509_extensions_server"
#     vars:
#       is_ca: false
#       subject_alt_name:
#       - "{{ quay_svc.service.metadata.name }}.{{ quay_svc.service.metadata.namespace }}.svc"
#       - "{{ quay_route.route.spec.host }}"

# # openssl ansible modules does not provide CA signing yet, meant for 2.6
#   - name: Generate a Server cert
#     shell: >
#       openssl x509 -req -in "{{ tmp_folder_cert.path }}/server.csr"
#       -CA "{{ tmp_folder_cert.path }}/ca.crt" -CAkey "{{ tmp_folder_cert.path }}/ca.key"
#       -CAcreateserial -out "{{ tmp_folder_cert.path }}/server.crt" 
#       -extfile "{{ tmp_folder_cert.path }}/x509_extensions_server" -extensions custom_extensions      
