---
# Delete Objects
- name: Delete Quay App objects
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
    state: absent
  with_items:
  - quay-enterprise-app-role.yml.j2
  - quay-enterprise-app-rolebinding.yml.j2
  - quay-enterprise-app-service.yml.j2
  - quay-enterprise-app-route.yml.j2
  - quay-enterprise-app-secret.yml.j2
  - quay-enterprise-app-pvc.yml.j2
  - quay-enterprise-app.yml.j2

- name: Delete Quay Redis objects
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
    state: absent
  with_items:
  - quay-enterprise-redis.yml.j2
  - quay-enterprise-redis-service.yml.j2
  
- name: Delete Quay PostgreSQL objects
  openshift_raw:
    definition: "{{ lookup('template', '' + item ) | from_yaml }}"
    state: absent
  with_items:
  - quay-enterprise-postgresql-pvc.yml.j2
  - quay-enterprise-postgresql.yml.j2
  - quay-enterprise-postgresql-service.yml.j2


